language: c

compiler: gcc

addons:
  apt:
    sources:
    - sourceline: deb https://apt.kitware.com/ubuntu/ focal main
      key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    packages:
    - cmake
    - libglib2.0-0
    - libglib2.0-bin
    - libglib2.0-dev
    - libglib2.0-dev-bin
    - libglib2.0-data

script:
  - cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
  - cd build
  - cmake --build .
  - ctest --test-dir tests -C Debug --output_on_failure
